name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not main

jobs:
  build-and-deploy:
    permissions:
      pages: write # Grant write permission to the GITHUB_TOKEN for the pages scope
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your preferred Node.js version

      - name: Build # Replace with your build command if needed
        run: echo "No build step required for static HTML/CSS/JS"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # The directory containing your built site (usually the root for static pages)
          cname: koleo.rent # Add this line with your custom domain